sudo: true

language: php

php:
  - 7.1.9
  
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
  
before_install:
  - composer self-update
  - openssl aes-256-cbc -K $encrypted_70c23fbfe7fe_key -iv $encrypted_70c23fbfe7fe_iv -in privatekey.enc -out privatekey -d
  - chmod 600 ./privatekey
  - eval `ssh-agent`
  - ssh-add -k ./privatekey
  - ssh-add -l
install:
  - composer install
  
script:
  - composer install
  
after_script:
  - cat ./privatekey
  - rsync -r /home/travis/build/xiaodit/think-admin/* -e "ssh -o StrictHostKeyChecking=no -p ${XDPORT} -i ./privatekey" ${XDUSER}@${XDHOST}:${XDPATH}
