sudo: true

language: php

php:
  - 7.1.9
  
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
  
before_install:
  - composer self-update
  - openssl aes-256-cbc -K $encrypted_70c23fbfe7fe_key -iv $encrypted_70c23fbfe7fe_iv -in deployer.enc -out deployer -d
  - chmod 600 ./deployer
  - eval `ssh-agent`
  - ssh-add -k ./deployer
  - ssh-add -l
install:
  - composer install
  
script:
  - composer install
  
after_script:
  - cat ./deployer
  - rsync -r /home/travis/build/xiaodit/think-admin/* -e "ssh -o StrictHostKeyChecking=no -p ${XDPORT} -i ./deployer" ${XDUSER}@${XDHOST}:${XDPATH}
