sudo: true

language: php

php:
  - 7.1.9

cache:
  directories:
    - vendor
    - "$HOME/.composer/cache"

before_install:
  - openssl aes-256-cbc -K $encrypted_70c23fbfe7fe_key -iv $encrypted_70c23fbfe7fe_iv -in privatekey.enc -out privatekey -d

script:
  - composer install

after_script:
  - chmod 600 ./privatekey
  - cat ./privatekey
  - rsync -r /home/travis/build/xiaodit/think-admin/* -e "ssh -o StrictHostKeyChecking=no -i ./privatekey -p ${XDPORT}" ${XDUSER}@${XDHOST}:${XDPATH}
