sudo: true

language: php

php:
  - 7.1.9
  
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
  
before_install:
  - composer self-update
  
script:
  - composer install
  
after_script:
  - chmod 600 ./deployer
  - rsync -r /home/travis/build/xiaodit/think-admin/* -e "ssh -o StrictHostKeyChecking=no -i ./deployer -p ${XDPORT}" ${XDUSER}@${XDHOST}:${XDPATH}
